### ISSUE TITLE
Update workflow node to support latest timm version

### ISSUE THREAD

**Issue by Cybernetic-Ransomware** [snicolast/ComfyUI-IndexTTS2#16]
Hi,

I’m trying to run the IndexTTS2 workflow in ComfyUI, and I get the following error:
`cannot import name 'ImageNetInfo' from 'timm.data' 
(C:\LLM-VLM\ComfyUI\python_embeded\Lib\site-packages\timm\data\__init__.py)
`

Details:
- The ImageNetInfo class has been removed or relocated in newer versions of timm (>=1.0).
- Currently, the workflow node still imports ImageNetInfo and is incompatible with the latest timm.
- I would prefer not to downgrade timm for my environment.

Suggested fix:
- Update the workflow node to be compatible with the latest timm version.
- Remove or replace the ImageNetInfo import so that the workflow works with timm >=1.0.
- This change would allow users to run the workflow without needing to downgrade dependencies.

Thanks!
